### ISSUE TITLE
Still not available on Stackage

### ISSUE THREAD

**Issue by deemp** [qfpl/waargonaut#86]
Hi! I'm unsuccessfully trying to build a project with recommended extra-deps.

`stack.yaml`:
```yaml
resolver: lts-19.18

# some stuff ...

extra-deps:
  - waargonaut-0.8.0.2
  - digit-0.11@sha256:d3b42df305e64756505e46dabad32d08df3721b2f58e7c4741cfd6a73ccaaef2,3888
  - hoist-error-0.2.1.0@sha256:b7ccf72fe0dc2339a06956a0388115a33550cbe08089c7c2da310d1ef7aa7b9c,1353
  - lens-4.19.2@sha256:d4d704141d7c322bbfb746157b0709f3b966dfec92421f571c34069893af08cc,16062
  - natural-0.3.0.6@sha256:6149f7df782b5fa0d7e6685319fed73cacbe3efb0721acff4d2c34e0f6d92205,2042
  - witherable-0.3.5@sha256:9febcda439f514aec8f430bd3c75a7cda20b28978a8cbad1b2f8f097a3a16b42,1542
  - Cabal-3.2.1.0@sha256:8743076ec022296f9771d962000c9ca3a0fe02e68c37b992c63e382a675f791d,27482
  - template-haskell-2.16.0.0@sha256:71d8c2e92b712695cb4fd0be9cd1a41b05c25315e9748cfef1132bf4d02b6556,1917
```

`package.yaml`:
```yaml
dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - text
  - unordered-containers
  - containers
  - stm
  - wai
  - wai-logger
  - warp
  - servant
  - servant-server
  - websockets
  - wai-websockets
  - servant-websockets
  - wai-app-static
  - hashable
  - waargonaut
  - digit
  - hoist
  - lens
  - natural
  - witherable
  - Cabal
  - template-haskell

# some stuff ...
```

Without the last two (`Cabal` and `template-haskell`) got such message:
```console
Error: While constructing the build plan, the following exceptions were encountered:

Dependency cycle detected in packages:
    [aeson,monoidal-containers,witherable,aeson,backend]

In the dependencies for backend-0.1.0.0:
    hoist needed, but the stack configuration has no specified version (no package with that name found, perhaps there is a typo in a package's build-depends or an
          omission from the stack.yaml packages list?)
    witherable dependency cycle detected: witherable, monoidal-containers, witherable, aeson, backend
needed since backend is a build target.

In the dependencies for lens-4.19.2:
    Cabal-3.4.1.0 from stack configuration does not match >=1.10 && <3.3  (latest matching version is 3.2.1.0)
    template-haskell-2.17.0.0 from stack configuration does not match >=2.4 && <2.17  (latest matching version is 2.16.0.0)
needed due to backend-0.1.0.0 -> lens-4.19.2

In the dependencies for monoidal-containers-0.6.2.0:
    aeson dependency cycle detected: aeson, monoidal-containers, witherable, aeson, backend
    witherable dependency cycle detected: witherable, monoidal-containers, witherable, aeson, backend
needed due to backend-0.1.0.0 -> monoidal-containers-0.6.2.0

In the dependencies for servant-0.19:
    aeson dependency cycle detected: aeson, monoidal-containers, witherable, aeson, backend
needed due to backend-0.1.0.0 -> servant-0.19

In the dependencies for servant-server-0.19.1:
    aeson dependency cycle detected: aeson, monoidal-containers, witherable, aeson, backend
needed due to backend-0.1.0.0 -> servant-server-0.19.1

In the dependencies for servant-websockets-2.0.0:
    aeson dependency cycle detected: aeson, monoidal-containers, witherable, aeson, backend
needed due to backend-0.1.0.0 -> servant-websockets-2.0.0

In the dependencies for waargonaut-0.8.0.2:
    witherable dependency cycle detected: witherable, monoidal-containers, witherable, aeson, backend
needed due to backend-0.1.0.0 -> waargonaut-0.8.0.2

In the dependencies for wai-extra-3.1.12.1:
    aeson dependency cycle detected: aeson, monoidal-containers, witherable, aeson, backend
needed due to backend-0.1.0.0 -> wai-extra-3.1.12.1

Dependency cycle detected in packages:
    [witherable,monoidal-containers,witherable,aeson,backend]

Unknown package: witherable-class
```
